name: Prerelease Linux

on:
  release:
    types:
      - prereleased
    tags:
      - '*'

jobs:

  packaging-amd64:
    uses: newrelic/infrastructure-agent/.github/workflows/component_linux_packaging.yml@master
    secrets:
      DOCKER_HUB_ID: ${{secrets.OHAI_DOCKER_HUB_ID}}
      DOCKER_HUB_PASSWORD: ${{secrets.OHAI_DOCKER_HUB_PASSWORD}}
      GPG_MAIL: 'infrastructure-eng@newrelic.com'
      GPG_PASSPHRASE: ${{ secrets.OHAI_GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY_BASE64: ${{ secrets.OHAI_GPG_PRIVATE_KEY_BASE64 }} # base64 encoded
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      TAG:  ${{ github.event.release.tag_name }}
      ARCH: 'amd64'

  packaging-arm:
    uses: newrelic/infrastructure-agent/.github/workflows/component_linux_packaging.yml@master
    secrets:
      DOCKER_HUB_ID: ${{secrets.OHAI_DOCKER_HUB_ID}}
      DOCKER_HUB_PASSWORD: ${{secrets.OHAI_DOCKER_HUB_PASSWORD}}
      GPG_MAIL: 'infrastructure-eng@newrelic.com'
      GPG_PASSPHRASE: ${{ secrets.OHAI_GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY_BASE64: ${{ secrets.OHAI_GPG_PRIVATE_KEY_BASE64 }} # base64 encoded
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      TAG:  ${{ github.event.release.tag_name }}
      ARCH: 'arm'

  packaging-arm64:
    uses: newrelic/infrastructure-agent/.github/workflows/component_linux_packaging.yml@master
    secrets:
      DOCKER_HUB_ID: ${{secrets.OHAI_DOCKER_HUB_ID}}
      DOCKER_HUB_PASSWORD: ${{secrets.OHAI_DOCKER_HUB_PASSWORD}}
      GPG_MAIL: 'infrastructure-eng@newrelic.com'
      GPG_PASSPHRASE: ${{ secrets.OHAI_GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY_BASE64: ${{ secrets.OHAI_GPG_PRIVATE_KEY_BASE64 }} # base64 encoded
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      TAG:  ${{ github.event.release.tag_name }}
      ARCH: 'arm64'

  packaging-legacy:
    uses: newrelic/infrastructure-agent/.github/workflows/component_linux_packaging.yml@master
    secrets:
      DOCKER_HUB_ID: ${{secrets.OHAI_DOCKER_HUB_ID}}
      DOCKER_HUB_PASSWORD: ${{secrets.OHAI_DOCKER_HUB_PASSWORD}}
      GPG_MAIL: 'infrastructure-eng@newrelic.com'
      GPG_PASSPHRASE: ${{ secrets.OHAI_GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY_BASE64: ${{ secrets.OHAI_GPG_PRIVATE_KEY_BASE64 }} # base64 encoded
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      TAG:  ${{ github.event.release.tag_name }}
      ARCH: 'legacy'


